version: "3.9"
services:
  worker:
    build: .
    environment:
      DATABASE_URL : $DATABASE_URL 
      OWNER_ID : $OWNER_ID 
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN  # defaults to None
